import os, difflib
from datetime import datetime, timezone
from distutils.file_util import write_file

from diff_generator.file_utils.utils import read_file, get_all_file_paths_recursive


def file_mtime(path: str) -> str:
    t = datetime.fromtimestamp(os.stat(path).st_mtime,
                               timezone.utc)
    return t.astimezone().isoformat()


def generate_html_diff_folders(folder1_path: str, folder2_path: str, extensions: list[str], just_context: bool = True, context_lines: int = 5):
    for file1_path in get_all_file_paths_recursive(folder1_path, extensions):
        diff = generate_html_diff_files(file1_path, file1_path.replace(folder1_path, folder2_path), just_context, context_lines)
        write_file("./output/" + file1_path + ".diff", diff)


# returns the html diff text generated by diffutils (NOTE: does not create a file)
def generate_html_diff_files(file1_path: str, file2_path: str, just_context: bool = True, context_lines: int = 5) -> str:
    diff = difflib.HtmlDiff(wrapcolumn=95).make_file(file_mtime(file1_path),
                                                     file_mtime(file2_path),
                                                     read_file(file1_path),
                                                     read_file(file2_path),
                                                     context=just_context,
                                                     numlines=context_lines)
    return diff
