# this generates a html patch file based on commit1 and commit2 folders

import difflib

from file_manager_utils import get_all_file_paths_recursive, write_to_file, get_file_path, read_file, generate_output_path


def is_file_changed(diff: str) -> bool:
    first_occurrence = diff.find("<td>&nbsp;No Differences Found&nbsp;</td>")
    if first_occurrence > -1:
        return diff.find("<td>&nbsp;No Differences Found&nbsp;</td>", first_occurrence) < 0
    return True


def generate_html_diff_folders(folder1_path: str,
                               folder2_path: str,
                               included_extensions: list[str],
                               excluded_extensions: list[str],
                               output_path: str,
                               just_context: bool = True,
                               context_lines: int = 5,
                               word_wrap: bool = False):
    base_output_folder_path = generate_output_path(folder1_path, folder2_path)
    for file1_path in get_all_file_paths_recursive(folder1_path, included_extensions, excluded_extensions):
        diff = generate_html_diff_files(get_file_path("", file1_path),
                                        get_file_path("", file1_path.replace(folder1_path, folder2_path)),
                                        just_context,
                                        context_lines,
                                        word_wrap=word_wrap)

        if not is_file_changed(diff):
            continue

        file1_path = file1_path.replace("./", "")
        new_path_starting_index = file1_path.find("extracted-")
        if new_path_starting_index == -1:  # because this can be a not extracted file
            new_path_starting_index = 0
        file1_path = file1_path[file1_path.find('\\', new_path_starting_index):]
        write_to_file(diff,
                      get_file_path("", output_path,
                                    absolute=True) + "/" + base_output_folder_path + file1_path + ".diff.html")


# returns the html diff text generated by diffutils (NOTE: does not create a file)
def generate_html_diff_files(file1_path: str,
                             file2_path: str,
                             just_context: bool = True,
                             context_lines: int = 5,
                             word_wrap: bool = False) -> str:
    html_diff = difflib.HtmlDiff(wrapcolumn=90) if word_wrap else difflib.HtmlDiff()
    diff = html_diff.make_file(read_file(file1_path, default="", as_str=False),
                               read_file(file2_path, default="", as_str=False),
                               file1_path,
                               file2_path,
                               context=just_context,
                               numlines=context_lines)
    return diff
