# this generates a html patch file based on commit1 and commit2 folders

import difflib
from datetime import datetime

from file_manager_utils import get_all_file_paths_recursive, write_to_file, get_file_path, read_file


def is_file_changed(diff: str) -> bool:
    first_occurrence = diff.find("<td>&nbsp;No Differences Found&nbsp;</td>")
    if first_occurrence > -1:
        return diff.find("<td>&nbsp;No Differences Found&nbsp;</td>", first_occurrence) < 0
    return True


def get_changeset_names(folder1_path: str, folder2_path: str) -> str:
    folder1_path = folder1_path.replace("./", "").replace("extracted-", "")
    folder2_path = folder2_path.replace("./", "").replace("extracted-", "")
    return folder1_path[folder1_path.rfind("/") + 1:] + "--" + folder2_path[folder2_path.find("/") + 1:]


def generate_html_diff_folders(folder1_path: str,
                               folder2_path: str,
                               included_extensions: list[str],
                               excluded_extensions: list[str],
                               output_path: str,
                               just_context: bool = True,
                               context_lines: int = 5):
    base_output_folder_path = get_changeset_names(folder1_path, folder2_path) + "--" + datetime.utcnow().strftime(
        '%Y-%m-%d--%H_%M_%S.%F')[:-3]
    for file1_path in get_all_file_paths_recursive(folder1_path, included_extensions, excluded_extensions):
        diff = generate_html_diff_files(get_file_path("", file1_path),
                                        get_file_path("",
                                                      file1_path.replace(folder1_path[
                                                                         folder1_path.find("/extracted-") + len(
                                                                             "/extracted-") + 1:],
                                                                         folder2_path[
                                                                         folder2_path.find("/extracted-") + len(
                                                                             "/extracted-") + 1:])),
                                        just_context,
                                        context_lines)

        if not is_file_changed(diff):
            continue

        file1_path = file1_path.replace("./", "")
        file1_path = file1_path[file1_path.find('\\', file1_path.find("extracted-")):]
        write_to_file(diff,
                      get_file_path("", output_path,
                                    absolute=True) + "/" + base_output_folder_path + file1_path + ".diff.html")


# returns the html diff text generated by diffutils (NOTE: does not create a file)
def generate_html_diff_files(file1_path: str, file2_path: str, just_context: bool = True,
                             context_lines: int = 5) -> str:
    diff = difflib.HtmlDiff(wrapcolumn=95).make_file(read_file(file1_path, default="", as_str=False),
                                                     read_file(file2_path, default="", as_str=False),
                                                     file1_path,
                                                     file2_path,
                                                     context=just_context,
                                                     numlines=context_lines)
    return diff
